### ISSUE TITLE
About the project progress

### ISSUE THREAD

**Issue by manjusaka999** [explabs-ai/projectaile#1]
I'd like to say that this is an amazing idea, and it would be incredibly convenient if it were realized.May I ask about the progress of this project? To be honest, I am very interested in SC-FEGAN and hope to see the implementation of this interesting project as soon as possible.

Best wishes.

**Comment by abtExp** [comment]
Hi @manjusaka999 , Thanks for your interest. The SC-FEGAN Project implementation is almost complete and i'll be uploading the code on the main repo [https://github.com/abtExp/arxivr](here) by this weekend itself as it's been on hold for very long time. But i'm getting back on track and i've implemented most of the code, just need to test a few things and i'll upload. As for this project ( ProjectAIle ), i still have a few things to figure out like the integration methods and how i can automate most of the processes and keep it integrated with my other project [https://github.com/explabs-ai/dlflow](dlflow) for easily creating and running ML project pipelines through an interactive CLI app. So it'll be a while before i release this project in beta. But if your main interest is SC-FEGAN, stay tuned for the release this weekend. For this project, it will be a while, maybe i'll release the beta on this and the dlflow project in January 2021.
Once again, thanks for your interest it gives me motivation to keep up with these projects and i'm trying my best to get things going faster.

**Comment by manjusaka999** [comment]
> Hi @manjusaka999 , Thanks for your interest. The SC-FEGAN Project implementation is almost complete and i'll be uploading the code on the main repo [here](https://github.com/abtExp/arxivr) by this weekend itself as it's been on hold for very long time. But i'm getting back on track and i've implemented most of the code, just need to test a few things and i'll upload. As for this project ( ProjectAIle ), i still have a few things to figure out like the integration methods and how i can automate most of the processes and keep it integrated with my other project [dlflow](https://github.com/explabs-ai/dlflow) for easily creating and running ML project pipelines through an interactive CLI app. So it'll be a while before i release this project in beta. But if your main interest is SC-FEGAN, stay tuned for the release this weekend. For this project, it will be a while, maybe i'll release the beta on this and the dlflow project in January 2021.
> Once again, thanks for your interest it gives me motivation to keep up with these projects and i'm trying my best to get things going faster.

Thank you for your detailed reply and your outstanding work. I have the same interest in this project as SC-FEGAN and wish you an early breakthrough!
